test = {
    "data": [
        {
            "id": "dp2-18",
            "name": "Uxie",
            "supertype": "Pokémon",
            "subtypes": ["Basic"],
            "level": "50",
            "hp": "60",
            "types": ["Psychic"],
            "abilities": [
                {
                    "name": "Memory Out",
                    "text": "Once during your opponent's turn, if Uxie is damaged by an opponent's attack (even if Uxie is Knocked Out), you may use this power. The Attacking Pokémon can't use that attack during your opponent's next turn.",
                    "type": "Poké-Power",
                }
            ],
            "attacks": [
                {
                    "name": "Mind Off",
                    "cost": ["Psychic"],
                    "convertedEnergyCost": 1,
                    "damage": "10+",
                    "text": "If you have Mesprit and Azelf in play, this attack does 10 damage plus 20 more damage and the Defending Pokémon is now Asleep.",
                }
            ],
            "weaknesses": [{"type": "Psychic", "value": "+20"}],
            "retreatCost": ["Colorless"],
            "convertedRetreatCost": 1,
            "set": {
                "id": "dp2",
                "name": "Mysterious Treasures",
                "series": "Diamond & Pearl",
                "printedTotal": 123,
                "total": 124,
                "legalities": {"unlimited": "Legal"},
                "ptcgoCode": "MT",
                "releaseDate": "2007/08/01",
                "updatedAt": "2018/03/04 10:35:00",
                "images": {
                    "symbol": "https://images.pokemontcg.io/dp2/symbol.png",
                    "logo": "https://images.pokemontcg.io/dp2/logo.png",
                },
            },
            "number": "18",
            "artist": "Ryo Ueda",
            "rarity": "Rare Holo",
            "flavorText": 'Known as "The Being of Knowledge." It is said that it can wipe out the memory of those who see its eyes.',
            "nationalPokedexNumbers": [480],
            "legalities": {"unlimited": "Legal"},
            "images": {
                "small": "https://images.pokemontcg.io/dp2/18.png",
                "large": "https://images.pokemontcg.io/dp2/18_hires.png",
            },
            "tcgplayer": {
                "url": "https://prices.pokemontcg.io/tcgplayer/dp2-18",
                "updatedAt": "2024/06/08",
                "prices": {
                    "holofoil": {
                        "low": 2.99,
                        "mid": 4.2,
                        "high": 10.99,
                        "market": 8.27,
                        "directLow": None,
                    },
                    "reverseHolofoil": {
                        "low": 1.68,
                        "mid": 3.95,
                        "high": 4.6,
                        "market": 4.47,
                        "directLow": None,
                    },
                },
            },
            "cardmarket": {
                "url": "https://prices.pokemontcg.io/cardmarket/dp2-18",
                "updatedAt": "2024/06/08",
                "prices": {
                    "averageSellPrice": 6.6,
                    "lowPrice": 0.75,
                    "trendPrice": 5.62,
                    "germanProLow": 0.0,
                    "suggestedPrice": 0.0,
                    "reverseHoloSell": 0.77,
                    "reverseHoloLow": 0.75,
                    "reverseHoloTrend": 3.18,
                    "lowPriceExPlus": 1.7,
                    "avg1": 3.5,
                    "avg7": 7.67,
                    "avg30": 4.9,
                    "reverseHoloAvg1": 0.75,
                    "reverseHoloAvg7": 1.57,
                    "reverseHoloAvg30": 2.38,
                },
            },
        },
        {
            "id": "bw10-36",
            "name": "Uxie",
            "supertype": "Pokémon",
            "subtypes": ["Basic"],
            "hp": "60",
            "types": ["Psychic"],
            "attacks": [
                {
                    "name": "Psypower",
                    "cost": ["Psychic"],
                    "convertedEnergyCost": 1,
                    "damage": "",
                    "text": "Put 3 damage counters on your opponent's Pokémon in any way you like.",
                }
            ],
            "weaknesses": [{"type": "Psychic", "value": "×2"}],
            "retreatCost": ["Colorless"],
            "convertedRetreatCost": 1,
            "set": {
                "id": "bw10",
                "name": "Plasma Blast",
                "series": "Black & White",
                "printedTotal": 101,
                "total": 105,
                "legalities": {"unlimited": "Legal", "expanded": "Legal"},
                "ptcgoCode": "PLB",
                "releaseDate": "2013/08/14",
                "updatedAt": "2018/03/04 10:35:00",
                "images": {
                    "symbol": "https://images.pokemontcg.io/bw10/symbol.png",
                    "logo": "https://images.pokemontcg.io/bw10/logo.png",
                },
            },
            "number": "36",
            "artist": "Sumiyoshi Kizuki",
            "rarity": "Rare",
            "flavorText": "When Uxie flew, people gained the ability to solve problems. It was the birth of knowledge.",
            "nationalPokedexNumbers": [480],
            "legalities": {"unlimited": "Legal", "expanded": "Legal"},
            "images": {
                "small": "https://images.pokemontcg.io/bw10/36.png",
                "large": "https://images.pokemontcg.io/bw10/36_hires.png",
            },
            "tcgplayer": {
                "url": "https://prices.pokemontcg.io/tcgplayer/bw10-36",
                "updatedAt": "2024/06/08",
                "prices": {
                    "normal": {
                        "low": 0.21,
                        "mid": 0.41,
                        "high": 2.43,
                        "market": 0.41,
                        "directLow": 0.25,
                    },
                    "reverseHolofoil": {
                        "low": 0.51,
                        "mid": 2.48,
                        "high": 3.99,
                        "market": 3.22,
                        "directLow": None,
                    },
                },
            },
            "cardmarket": {
                "url": "https://prices.pokemontcg.io/cardmarket/bw10-36",
                "updatedAt": "2024/06/08",
                "prices": {
                    "averageSellPrice": 0.56,
                    "lowPrice": 0.1,
                    "trendPrice": 0.52,
                    "germanProLow": 0.0,
                    "suggestedPrice": 0.0,
                    "reverseHoloSell": 0.34,
                    "reverseHoloLow": 0.75,
                    "reverseHoloTrend": 1.38,
                    "lowPriceExPlus": 0.15,
                    "avg1": 0.55,
                    "avg7": 0.48,
                    "avg30": 0.68,
                    "reverseHoloAvg1": 0.34,
                    "reverseHoloAvg7": 1.46,
                    "reverseHoloAvg30": 0.75,
                },
            },
        },
        {
            "id": "sm6-41",
            "name": "Uxie",
            "supertype": "Pokémon",
            "subtypes": ["Basic"],
            "hp": "60",
            "types": ["Psychic"],
            "attacks": [
                {
                    "name": "Memory Skip",
                    "cost": ["Psychic"],
                    "convertedEnergyCost": 1,
                    "damage": "30",
                    "text": "Choose 1 of your opponent's Active Pokémon's attacks. That Pokémon can't use that attack during your opponent's next turn.",
                }
            ],
            "weaknesses": [{"type": "Psychic", "value": "×2"}],
            "retreatCost": ["Colorless"],
            "convertedRetreatCost": 1,
            "set": {
                "id": "sm6",
                "name": "Forbidden Light",
                "series": "Sun & Moon",
                "printedTotal": 131,
                "total": 150,
                "legalities": {"unlimited": "Legal", "expanded": "Legal"},
                "ptcgoCode": "FLI",
                "releaseDate": "2018/05/04",
                "updatedAt": "2019/02/19 23:25:00",
                "images": {
                    "symbol": "https://images.pokemontcg.io/sm6/symbol.png",
                    "logo": "https://images.pokemontcg.io/sm6/logo.png",
                },
            },
            "number": "41",
            "artist": "Shin Nagasawa",
            "rarity": "Uncommon",
            "flavorText": "It is said that its emergence gave humans the intelligence to improve their quality of life.",
            "nationalPokedexNumbers": [480],
            "legalities": {"unlimited": "Legal", "expanded": "Legal"},
            "images": {
                "small": "https://images.pokemontcg.io/sm6/41.png",
                "large": "https://images.pokemontcg.io/sm6/41_hires.png",
            },
            "tcgplayer": {
                "url": "https://prices.pokemontcg.io/tcgplayer/sm6-41",
                "updatedAt": "2024/06/08",
                "prices": {
                    "reverseHolofoil": {
                        "low": 0.25,
                        "mid": 0.41,
                        "high": 8.98,
                        "market": 0.41,
                        "directLow": None,
                    },
                    "normal": {
                        "low": 0.1,
                        "mid": 0.25,
                        "high": 1.23,
                        "market": 0.16,
                        "directLow": 0.1,
                    },
                },
            },
            "cardmarket": {
                "url": "https://prices.pokemontcg.io/cardmarket/sm6-41",
                "updatedAt": "2024/06/08",
                "prices": {
                    "averageSellPrice": 0.11,
                    "lowPrice": 0.02,
                    "trendPrice": 0.11,
                    "germanProLow": 0.0,
                    "suggestedPrice": 0.0,
                    "reverseHoloSell": 0.39,
                    "reverseHoloLow": 0.15,
                    "reverseHoloTrend": 0.47,
                    "lowPriceExPlus": 0.02,
                    "avg1": 0.04,
                    "avg7": 0.08,
                    "avg30": 0.11,
                    "reverseHoloAvg1": 0.35,
                    "reverseHoloAvg7": 0.46,
                    "reverseHoloAvg30": 0.57,
                },
            },
        },
        {
            "id": "dp6-43",
            "name": "Uxie",
            "supertype": "Pokémon",
            "subtypes": ["Basic"],
            "level": "55",
            "hp": "70",
            "types": ["Psychic"],
            "abilities": [
                {
                    "name": "Set Up",
                    "text": "Once during your turn, when you put Uxie from your hand onto your Bench, you may draw cards until you have 7 cards in your hand.",
                    "type": "Poké-Power",
                }
            ],
            "attacks": [
                {
                    "name": "Psychic Restore",
                    "cost": ["Colorless"],
                    "convertedEnergyCost": 1,
                    "damage": "20",
                    "text": "You may put Uxie and all cards attached to it on the bottom of your deck in any order.",
                }
            ],
            "weaknesses": [{"type": "Psychic", "value": "+20"}],
            "retreatCost": ["Colorless"],
            "convertedRetreatCost": 1,
            "set": {
                "id": "dp6",
                "name": "Legends Awakened",
                "series": "Diamond & Pearl",
                "printedTotal": 146,
                "total": 146,
                "legalities": {"unlimited": "Legal"},
                "ptcgoCode": "LA",
                "releaseDate": "2008/08/01",
                "updatedAt": "2018/03/04 10:35:00",
                "images": {
                    "symbol": "https://images.pokemontcg.io/dp6/symbol.png",
                    "logo": "https://images.pokemontcg.io/dp6/logo.png",
                },
            },
            "number": "43",
            "artist": "Ken Sugimori",
            "rarity": "Rare",
            "flavorText": 'Known as "The Being of Knowledge." It is said that it can wipe out the memory of those who see its eyes.',
            "nationalPokedexNumbers": [480],
            "legalities": {"unlimited": "Legal"},
            "images": {
                "small": "https://images.pokemontcg.io/dp6/43.png",
                "large": "https://images.pokemontcg.io/dp6/43_hires.png",
            },
            "tcgplayer": {
                "url": "https://prices.pokemontcg.io/tcgplayer/dp6-43",
                "updatedAt": "2024/06/08",
                "prices": {
                    "normal": {
                        "low": 7.22,
                        "mid": 9.1,
                        "high": 12.99,
                        "market": 9.6,
                        "directLow": None,
                    },
                    "reverseHolofoil": {
                        "low": 8.99,
                        "mid": 12.42,
                        "high": 14.94,
                        "market": 14.23,
                        "directLow": None,
                    },
                },
            },
            "cardmarket": {
                "url": "https://prices.pokemontcg.io/cardmarket/dp6-43",
                "updatedAt": "2024/06/08",
                "prices": {
                    "averageSellPrice": 2.8,
                    "lowPrice": 1.0,
                    "trendPrice": 3.37,
                    "germanProLow": 0.0,
                    "suggestedPrice": 0.0,
                    "reverseHoloSell": 0.0,
                    "reverseHoloLow": 0.0,
                    "reverseHoloTrend": 2.21,
                    "lowPriceExPlus": 1.5,
                    "avg1": 3.25,
                    "avg7": 2.93,
                    "avg30": 2.97,
                    "reverseHoloAvg1": 2.45,
                    "reverseHoloAvg7": 2.1,
                    "reverseHoloAvg30": 1.87,
                },
            },
        },
        {
            "id": "sm11-83",
            "name": "Uxie",
            "supertype": "Pokémon",
            "subtypes": ["Basic"],
            "hp": "70",
            "types": ["Psychic"],
            "abilities": [
                {
                    "name": "Secret Territory",
                    "text": "If you have Mesprit and Azelf in play, apply Weakness for each Pokémon (both yours and your opponent's) as ×4 instead.",
                    "type": "Ability",
                }
            ],
            "attacks": [
                {
                    "name": "Psyshot",
                    "cost": ["Colorless", "Colorless", "Colorless"],
                    "convertedEnergyCost": 3,
                    "damage": "30",
                    "text": "",
                }
            ],
            "weaknesses": [{"type": "Psychic", "value": "×2"}],
            "retreatCost": ["Colorless"],
            "convertedRetreatCost": 1,
            "set": {
                "id": "sm11",
                "name": "Unified Minds",
                "series": "Sun & Moon",
                "printedTotal": 236,
                "total": 260,
                "legalities": {"unlimited": "Legal", "expanded": "Legal"},
                "ptcgoCode": "UNM",
                "releaseDate": "2019/08/02",
                "updatedAt": "2021/09/01 05:37:00",
                "images": {
                    "symbol": "https://images.pokemontcg.io/sm11/symbol.png",
                    "logo": "https://images.pokemontcg.io/sm11/logo.png",
                },
            },
            "number": "83",
            "artist": "kodama",
            "rarity": "Rare Holo",
            "flavorText": 'Known as "The Being of Knowledge." It is said that it can wipe out the memory of those who see its eyes.',
            "nationalPokedexNumbers": [480],
            "legalities": {"unlimited": "Legal", "expanded": "Legal"},
            "images": {
                "small": "https://images.pokemontcg.io/sm11/83.png",
                "large": "https://images.pokemontcg.io/sm11/83_hires.png",
            },
            "tcgplayer": {
                "url": "https://prices.pokemontcg.io/tcgplayer/sm11-83",
                "updatedAt": "2024/06/08",
                "prices": {
                    "reverseHolofoil": {
                        "low": 0.4,
                        "mid": 0.61,
                        "high": 4.99,
                        "market": 0.52,
                        "directLow": None,
                    },
                    "holofoil": {
                        "low": 0.25,
                        "mid": 0.6,
                        "high": 2.0,
                        "market": 0.53,
                        "directLow": 0.53,
                    },
                },
            },
            "cardmarket": {
                "url": "https://prices.pokemontcg.io/cardmarket/sm11-83",
                "updatedAt": "2024/06/08",
                "prices": {
                    "averageSellPrice": 0.7,
                    "lowPrice": 0.25,
                    "trendPrice": 0.77,
                    "germanProLow": 0.0,
                    "suggestedPrice": 0.0,
                    "reverseHoloSell": 0.78,
                    "reverseHoloLow": 0.25,
                    "reverseHoloTrend": 1.35,
                    "lowPriceExPlus": 0.3,
                    "avg1": 0.99,
                    "avg7": 0.76,
                    "avg30": 0.78,
                    "reverseHoloAvg1": 1.0,
                    "reverseHoloAvg7": 1.02,
                    "reverseHoloAvg30": 1.31,
                },
            },
        },
        {
            "id": "dp6-146",
            "name": "Uxie LV.X",
            "supertype": "Pokémon",
            "subtypes": ["Level-Up"],
            "level": "X",
            "hp": "90",
            "types": ["Psychic"],
            "evolvesFrom": "Uxie",
            "rules": [
                "Put this card onto your Active Uxie. Uxie LV.X can use any attack, Poké-Power, or Poké-Body from its previous level."
            ],
            "abilities": [
                {
                    "name": "Trade Off",
                    "text": "Once during your turn (before your attack), you may look at the top 2 cards of your deck, choose 1 of them, and put it into your hand. Put the other card on the bottom of your deck. This power can't be used if Uxie is affected by a Special Condition. You can't use more than 1 Trade Off Poké-Power each turn.",
                    "type": "Poké-Power",
                }
            ],
            "attacks": [
                {
                    "name": "Zen Blade",
                    "cost": ["Colorless", "Colorless"],
                    "convertedEnergyCost": 2,
                    "damage": "60",
                    "text": "Uxie can't use Zen Blade during your next turn.",
                }
            ],
            "weaknesses": [{"type": "Psychic", "value": "×2"}],
            "retreatCost": ["Colorless"],
            "convertedRetreatCost": 1,
            "set": {
                "id": "dp6",
                "name": "Legends Awakened",
                "series": "Diamond & Pearl",
                "printedTotal": 146,
                "total": 146,
                "legalities": {"unlimited": "Legal"},
                "ptcgoCode": "LA",
                "releaseDate": "2008/08/01",
                "updatedAt": "2018/03/04 10:35:00",
                "images": {
                    "symbol": "https://images.pokemontcg.io/dp6/symbol.png",
                    "logo": "https://images.pokemontcg.io/dp6/logo.png",
                },
            },
            "number": "146",
            "artist": "Shizurow",
            "rarity": "Rare Holo LV.X",
            "nationalPokedexNumbers": [480],
            "legalities": {"unlimited": "Legal"},
            "images": {
                "small": "https://images.pokemontcg.io/dp6/146.png",
                "large": "https://images.pokemontcg.io/dp6/146_hires.png",
            },
            "tcgplayer": {
                "url": "https://prices.pokemontcg.io/tcgplayer/dp6-146",
                "updatedAt": "2024/06/08",
                "prices": {
                    "holofoil": {
                        "low": 42.0,
                        "mid": 42.99,
                        "high": 46.87,
                        "market": 46.05,
                        "directLow": None,
                    }
                },
            },
            "cardmarket": {
                "url": "https://prices.pokemontcg.io/cardmarket/dp6-146",
                "updatedAt": "2024/06/08",
                "prices": {
                    "averageSellPrice": 31.0,
                    "lowPrice": 8.99,
                    "trendPrice": 34.56,
                    "germanProLow": 0.0,
                    "suggestedPrice": 0.0,
                    "reverseHoloSell": 0.0,
                    "reverseHoloLow": 0.0,
                    "reverseHoloTrend": 32.59,
                    "lowPriceExPlus": 39.95,
                    "avg1": 34.63,
                    "avg7": 34.32,
                    "avg30": 33.43,
                    "reverseHoloAvg1": 60.0,
                    "reverseHoloAvg7": 28.06,
                    "reverseHoloAvg30": 22.54,
                },
            },
        },
        {
            "id": "swsh10-65",
            "name": "Uxie",
            "supertype": "Pokémon",
            "subtypes": ["Basic"],
            "hp": "70",
            "types": ["Psychic"],
            "attacks": [
                {
                    "name": "Wise Guidance",
                    "cost": ["Colorless"],
                    "convertedEnergyCost": 1,
                    "damage": "",
                    "text": "Search your deck for a card and put it into your hand. Then, shuffle your deck.",
                },
                {
                    "name": "Psyshot",
                    "cost": ["Psychic"],
                    "convertedEnergyCost": 1,
                    "damage": "20",
                    "text": "",
                },
            ],
            "weaknesses": [{"type": "Darkness", "value": "×2"}],
            "resistances": [{"type": "Fighting", "value": "-30"}],
            "retreatCost": ["Colorless"],
            "convertedRetreatCost": 1,
            "set": {
                "id": "swsh10",
                "name": "Astral Radiance",
                "series": "Sword & Shield",
                "printedTotal": 189,
                "total": 216,
                "legalities": {
                    "unlimited": "Legal",
                    "standard": "Legal",
                    "expanded": "Legal",
                },
                "ptcgoCode": "ASR",
                "releaseDate": "2022/05/27",
                "updatedAt": "2022/05/27 09:45:00",
                "images": {
                    "symbol": "https://images.pokemontcg.io/swsh10/symbol.png",
                    "logo": "https://images.pokemontcg.io/swsh10/logo.png",
                },
            },
            "number": "65",
            "artist": "sui",
            "rarity": "Uncommon",
            "flavorText": "It is said that its emergence gave humans the intelligence to improve their quality of life.",
            "nationalPokedexNumbers": [480],
            "legalities": {
                "unlimited": "Legal",
                "standard": "Legal",
                "expanded": "Legal",
            },
            "regulationMark": "F",
            "images": {
                "small": "https://images.pokemontcg.io/swsh10/65.png",
                "large": "https://images.pokemontcg.io/swsh10/65_hires.png",
            },
            "tcgplayer": {
                "url": "https://prices.pokemontcg.io/tcgplayer/swsh10-65",
                "updatedAt": "2024/06/08",
                "prices": {
                    "reverseHolofoil": {
                        "low": 0.04,
                        "mid": 0.17,
                        "high": 2.0,
                        "market": 0.16,
                        "directLow": None,
                    },
                    "normal": {
                        "low": 0.01,
                        "mid": 0.08,
                        "high": 999.0,
                        "market": 0.03,
                        "directLow": None,
                    },
                },
            },
            "cardmarket": {
                "url": "https://prices.pokemontcg.io/cardmarket/swsh10-65",
                "updatedAt": "2024/06/08",
                "prices": {
                    "averageSellPrice": 0.04,
                    "lowPrice": 0.01,
                    "trendPrice": 0.05,
                    "germanProLow": 0.0,
                    "suggestedPrice": 0.0,
                    "reverseHoloSell": 0.21,
                    "reverseHoloLow": 0.03,
                    "reverseHoloTrend": 0.22,
                    "lowPriceExPlus": 0.01,
                    "avg1": 0.1,
                    "avg7": 0.05,
                    "avg30": 0.05,
                    "reverseHoloAvg1": 0.02,
                    "reverseHoloAvg7": 0.22,
                    "reverseHoloAvg30": 0.23,
                },
            },
        },
    ],
    "page": 1,
    "pageSize": 250,
    "count": 7,
    "totalCount": 7,
}
