"""Species and Pokemon models

Revision ID: a969fbf43598
Revises:
Create Date: 2024-06-18 23:37:11.645736

"""

import csv

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from williott.pokemon.models import Species, Pokemon


# revision identifiers, used by Alembic.
revision: str = "a969fbf43598"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "species",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generation_id", sa.Integer(), nullable=False),
        sa.Column("evolves_from_species_id", sa.Integer(), nullable=True),
        sa.Column("evolution_chain_id", sa.Integer(), nullable=False),
        sa.Column("color_id", sa.Integer(), nullable=False),
        sa.Column("shape_id", sa.Integer(), nullable=False),
        sa.Column("habitat_id", sa.Integer(), nullable=False),
        sa.Column("gender_rate", sa.Integer(), nullable=False),
        sa.Column("capture_rate", sa.Integer(), nullable=False),
        sa.Column("base_happiness", sa.Integer(), nullable=False),
        sa.Column("is_baby", sa.Boolean(), nullable=False),
        sa.Column("hatch_counter", sa.Integer(), nullable=False),
        sa.Column("has_gender_differences", sa.Boolean(), nullable=False),
        sa.Column("growth_rate_id", sa.Integer(), nullable=False),
        sa.Column("forms_switchable", sa.Boolean(), nullable=False),
        sa.Column("is_legendary", sa.Boolean(), nullable=False),
        sa.Column("is_mythical", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("conquest_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("base_experience", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["species_id"],
            ["species.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    # ### end Alembic commands ###

    # Data migration:

    all_species = []
    folder = "migration_data/a969fbf43598_species_and_pokemon_models"

    with open(f"{folder}/species.csv") as f:
        reader = csv.DictReader(f, delimiter=",")
        for row in reader:
            all_species.append(
                {
                    **row,
                    "is_baby": int(row["is_baby"]),
                    "has_gender_differences": int(row["has_gender_differences"]),
                    "forms_switchable": int(row["forms_switchable"]),
                    "is_legendary": int(row["is_legendary"]),
                    "is_mythical": int(row["is_mythical"]),
                }
            )

    all_pokemon = []

    with open(f"{folder}/pokemon.csv") as f:
        reader = csv.DictReader(f, delimiter=",")
        for row in reader:
            all_pokemon.append(
                {
                    **row,
                    "is_default": int(row["is_default"]),
                }
            )

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    session.bulk_insert_mappings(Species, all_species)  # type: ignore
    session.bulk_insert_mappings(Pokemon, all_pokemon)  # type: ignore

    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pokemon")
    op.drop_table("species")
    # ### end Alembic commands ###
