"""add pokemon models

Revision ID: afc34ae2dfca
Revises:
Create Date: 2024-06-22 00:04:43.781467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from williott.data_entry import data_entry


# revision identifiers, used by Alembic.
revision: str = "afc34ae2dfca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation",
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "language",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("iso639", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("iso3166", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("official", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "species",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("generation_id", sa.Integer(), nullable=False),
        sa.Column("evolves_from_species_id", sa.Integer(), nullable=True),
        sa.Column("evolution_chain_id", sa.Integer(), nullable=True),
        sa.Column("color_id", sa.Integer(), nullable=True),
        sa.Column("shape_id", sa.Integer(), nullable=True),
        sa.Column("habitat_id", sa.Integer(), nullable=True),
        sa.Column("gender_rate", sa.Integer(), nullable=False),
        sa.Column("capture_rate", sa.Integer(), nullable=False),
        sa.Column("base_happiness", sa.Integer(), nullable=True),
        sa.Column("is_baby", sa.Boolean(), nullable=False),
        sa.Column("hatch_counter", sa.Integer(), nullable=True),
        sa.Column("has_gender_differences", sa.Boolean(), nullable=False),
        sa.Column("growth_rate_id", sa.Integer(), nullable=True),
        sa.Column("forms_switchable", sa.Boolean(), nullable=False),
        sa.Column("is_legendary", sa.Boolean(), nullable=False),
        sa.Column("is_mythical", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("conquest_order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["generation_id"],
            ["generation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_table(
        "description",
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
        ),
        sa.ForeignKeyConstraint(
            ["species_id"],
            ["species.id"],
        ),
        sa.PrimaryKeyConstraint("species_id", "version_id", "language_id"),
    )
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("base_experience", sa.Integer(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["species_id"],
            ["species.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_table(
        "speciesname",
        sa.Column("species_id", sa.Integer(), nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("genus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
        ),
        sa.ForeignKeyConstraint(
            ["species_id"],
            ["species.id"],
        ),
        sa.PrimaryKeyConstraint("species_id", "language_id"),
    )
    # ### end Alembic commands ###

    data_entry()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("speciesname")
    op.drop_table("pokemon")
    op.drop_table("description")
    op.drop_table("species")
    op.drop_table("language")
    op.drop_table("generation")
    # ### end Alembic commands ###
